POST http://localhost:5000/api/salads
Content-Type: application/json

{
    "name": "Greek",
    "weight": 400,
    "inGredients": ["cheese", "tomato", "olives"],
    "souce":"oil",
    "dietType": "none",
    "spicy": false,
    "expired": "2025-09-17"
  }
