POST http://localhost:5000/api/salads
Content-Type: application/json

{
    "name": "New salad",
    "weight": 400,
    "inGredients": ["cheeken", "tomato"],
    "souce":"oil",
    "dietType": "none",
    "spicy": false,
    "expired": "2025-09-17"
  }
